# Header
menu:
  主页: /
  所有文章: /archives
  技术: /tech
  随笔: /life
  关于我: /about
  # 随笔: /tags/随笔

title: One Piece
# SubNav
subnav:
  github: "https://github.com/chocoluffy"
  weibo: "http://weibo.com/chocoluffy"
  rss: "/atom.xml"
  # rss: "http://feed.feedsky.com/litten"
  # zhihu: "#"
  #douban: "#"
  # mail: "mailto:luffy.yu@mail.utoronto.ca"
  facebook: "https://www.facebook.com/profile.php?id=100007218182748"
  #google: "#"
  # twitter: ""
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: UA-41207871-1
favicon:  ./source/favicon.png

#你的头像url
avatar: "http://ww3.sinaimg.cn/large/c5ee78b5gw1ez498sfwnuj208w08wmxt.jpg"
#是否开启分享
share_jia: true
share_addthis: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: false
disqus_shortname: chocoluffy
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
# friends:
#   奥巴马的博客: http://localhost:4000/
#   卡卡的美丽传说: http://localhost:4000/
#   本泽马的博客: http://localhost:4000/
#   吉格斯的博客: http://localhost:4000/
#   习大大大不同: http://localhost:4000/
#   托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 技术就是信仰
