language: node_js

node_js:
    - "7"

cache:
    apt: true
    directories:
        - node_modules

before_install:
    - export TZ='America/New_York'
    - npm install hexo-cli -g
    - chmod +x ./publish-to-gh-pages.sh

install:
    - npm install

script:
    - rsync -a hexo-douban ./node_modules/
    - rm -r hexo-douban/
    - hexo clean
    - hexo g

after_script:
    - ./publish-to-gh-pages.sh

branches:
    only:
        - hexo

env:
    global:
        - GH_REF: github.com/chocoluffy/chocoluffy.github.io.git
        