# Header
menu:
  首页: /
  存档: /archives
  关于: /about
rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- search
- category
- tag
- tagcloud
- archive
- weibo
- blogroll
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: